import networkx as nx
from typing import Dict, List, Any
from wavesync.engine.models import ServiceNode
from wavesync.engine.orchestrator import WaveSyncOrchestrator

def build_ai_detected_dag(
    service_configs: List[Dict[str, Any]], 
    ai_dependencies: Dict[str, List[str]]
) -> WaveSyncOrchestrator:
    """
    Integrates raw AI-detected dependencies directly into the graph engine to 
    construct a validated Directed Acyclic Graph (DAG).
    
    Args:
        service_configs: List of service definitions.
                         Example: [{"id": "Frontend", "priority": 1}]
        ai_dependencies: Dependency map generated by the AI agent.
                         Example: {"Frontend": ["Auth", "Payment"]}
                         
    Returns:
        WaveSyncOrchestrator: A fully validated NetworkX DAG orchestrator.
        
    Raises:
        MigrationCycleError: Throws detailed cycle paths if the AI hallucinated 
                             a circular dependency (e.g., A -> B -> A).
        InvalidServiceError: Throws if the AI maps a dependency to a non-existent service.
    """
    
    # 1. Transform raw AI signals into strict typed ServiceNode objects
    service_nodes = []
    
    for config in service_configs:
        service_id = config.get("id") or config.get("name")
        if not service_id:
            continue
            
        priority = config.get("priority", 5)
        
        # Bind the AI-detected dependencies specifically to this service
        depends_on = ai_dependencies.get(service_id, [])
        
        node = ServiceNode(
            id=service_id,
            priority=priority,
            depends_on=depends_on,
            metadata=config
        )
        service_nodes.append(node)
        
    # 2. Build the DAG and Validate
    # The WaveSyncOrchestrator internally initializes nx.DiGraph(), dynamic add_node(), 
    # add_edge(dependency -> service), and strictly runs nx.is_directed_acyclic_graph() 
    # to catch any AI hallucinations.
    orchestrator = WaveSyncOrchestrator(services=service_nodes)
    
    return orchestrator


if __name__ == "__main__":
    # Example test harnessing the AI integration
    mock_services = [
        {"id": "Frontend", "priority": 1},
        {"id": "Auth", "priority": 5},
        {"id": "Payment", "priority": 3}
    ]
    
    # AI Output from the previous Agent logic
    mock_ai_output = {
        "Frontend": ["Auth", "Payment"],
        "Auth": [],
        "Payment": ["Auth"]
    }
    
    print("Building DAG with AI detected dependencies...")
    orchestrator = build_ai_detected_dag(mock_services, mock_ai_output)
    
    print("DAG Successfully Validated!")
    print(f"Topological Sequence Exec: {orchestrator.get_serial_sequence()}")
